import { MigrationInterface, QueryRunner } from "typeorm";

export class RemoveBasedocumentExtension1761705055868 implements MigrationInterface {
    name = 'RemoveBasedocumentExtension1761705055868'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "master_division_list" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "division_code" character varying NOT NULL, "division_name" character varying NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0787a4d25369dcdaef1b749b567" UNIQUE ("division_code"), CONSTRAINT "UQ_57e6bba2a8a2b7410b6f1e5b96d" UNIQUE ("division_name"), CONSTRAINT "PK_1b5becd8ef33e24807802b31002" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "master_company_list" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_code" character varying NOT NULL, "company_name" character varying NOT NULL, "address" text, "phone_number" character varying, "email" character varying, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7059cfb6bfc547f32c437bc5a36" UNIQUE ("company_code"), CONSTRAINT "UQ_d61802732f1ba893d6b3b50a1e5" UNIQUE ("company_name"), CONSTRAINT "PK_7bb373ace3ac9398b162b5afec5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_type" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f838abdcbc6fc58de6db26c1e65" UNIQUE ("name"), CONSTRAINT "PK_a4ec97ac782ed598e0b28e66ccd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."master_client_list_status_enum" AS ENUM('Active', 'blacklist', 'cautious')`);
        await queryRunner.query(`CREATE TABLE "master_client_list" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "group" character varying(255), "contact_name" character varying(255) NOT NULL, "contact_position" character varying(255), "contact_email" character varying(255) NOT NULL, "contact_phone" character varying(50) NOT NULL, "referral_from" character varying(255), "date_of_first_project" date, "status" "public"."master_client_list_status_enum" NOT NULL DEFAULT 'Active', "priority_number" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "isWapu" boolean NOT NULL DEFAULT true, "type_id" integer NOT NULL, CONSTRAINT "PK_9f3371e686b5dd859bd9ae1db12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."identity_status_enum" AS ENUM('active', 'inactive', 'pending')`);
        await queryRunner.query(`CREATE TYPE "public"."identity_role_enum" AS ENUM('ADMIN', 'USER', 'MANAGER')`);
        await queryRunner.query(`CREATE TABLE "identity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "external_id" character varying(255) NOT NULL, "keycloak_id" character varying(255), "email" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "department" character varying(255), "job_title" character varying(255), "preferred_username" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "status" "public"."identity_status_enum" NOT NULL DEFAULT 'active', "role" "public"."identity_role_enum" NOT NULL DEFAULT 'USER', CONSTRAINT "UQ_44deca8dc7cf45dcc6731a7d194" UNIQUE ("external_id"), CONSTRAINT "UQ_2d12ecd5a215a1f5529660e4717" UNIQUE ("keycloak_id"), CONSTRAINT "UQ_0d9005670fa2ee7dcc48842f64d" UNIQUE ("email"), CONSTRAINT "PK_ff16a44186b286d5e626178f726" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_44deca8dc7cf45dcc6731a7d19" ON "identity" ("external_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d12ecd5a215a1f5529660e471" ON "identity" ("keycloak_id") `);
        await queryRunner.query(`CREATE TABLE "document_schema"."document_type" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "id" SERIAL NOT NULL, "type_name" character varying NOT NULL, "shorthand" character varying NOT NULL, CONSTRAINT "UQ_816f7c1492a755e45583c1d2d69" UNIQUE ("type_name"), CONSTRAINT "UQ_c1f5cc771e2ee40af6153cc29b1" UNIQUE ("shorthand"), CONSTRAINT "PK_2e1aa55eac1947ddf3221506edb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "document_schema"."master_document_list_document_status_enum" AS ENUM('DRAFT', 'PENDING', 'SIGNED', 'ACTIVE', 'ARCHIVED', 'EXPIRED', 'CANCELLED', 'REJECTED', 'FINALIZED')`);
        await queryRunner.query(`CREATE TABLE "document_schema"."master_document_list" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_number" character varying NOT NULL, "document_external_number" character varying NOT NULL, "document_name" character varying NOT NULL, "document_legal_date" character varying NOT NULL, "index_number" integer NOT NULL, "document_status" "document_schema"."master_document_list_document_status_enum" NOT NULL DEFAULT 'DRAFT', "mongo_document_id" character varying, "document_type_id" integer, "created_by" uuid, "master_division_list_id" uuid, "master_company_list_id" uuid, CONSTRAINT "UQ_a72bcfd1857d622a20208d75f1c" UNIQUE ("document_number"), CONSTRAINT "PK_2eac646c00fd6da6dc5b8c90b56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_schema"."surat_tugas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nama_pekerjaan" character varying NOT NULL, "deskripsi_pekerjaan" character varying NOT NULL, "tanggal_mulai" TIMESTAMP NOT NULL, "tanggal_selesai" TIMESTAMP NOT NULL, "lokasi" character varying NOT NULL, "type" character varying NOT NULL, "tanggal_surat_tugas" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying NOT NULL, "updated_by" character varying NOT NULL, "master_document_list_id" uuid, "client_id" uuid, "signer" uuid, CONSTRAINT "PK_42d23f8ba3f526be4a0b82eadb9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_schema"."tim_penugasan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL, "surat_tugas_id" uuid NOT NULL, "personnel_id" uuid NOT NULL, CONSTRAINT "PK_65b9073ebdd9e907d476ef4434d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_installment_trigger_type_enum" AS ENUM('milestone', 'event', 'date', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_installment_status_enum" AS ENUM('pending', 'due', 'cleared', 'requested', 'paid', 'issue')`);
        await queryRunner.query(`CREATE TABLE "payment_installment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pekerjaan_id" uuid NOT NULL, "installment_number" integer NOT NULL, "amount" numeric(19,4) NOT NULL, "percentage" numeric(5,2) NOT NULL, "trigger_type" "public"."payment_installment_trigger_type_enum" NOT NULL, "trigger_value" character varying, "project_milestone_id" uuid, "description" text NOT NULL, "status" "public"."payment_installment_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "due_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e16bfde5aa5b8c316ca7425d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pekerjaan_creation_status_enum" AS ENUM('created', 'in_progress', 'completed')`);
        await queryRunner.query(`CREATE TYPE "public"."pekerjaan_progress_status_enum" AS ENUM('on_track', 'at_risk', 'delayed', 'issue')`);
        await queryRunner.query(`CREATE TABLE "pekerjaan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_name" character varying NOT NULL, "project_description" character varying NOT NULL DEFAULT '', "spk_id" character varying NOT NULL, "team_member_structure" jsonb NOT NULL, "project_fee" numeric(19,4), "currency" character varying(3) NOT NULL DEFAULT 'IDR', "bank_name" character varying, "account_number" character varying, "account_name" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "creation_status" "public"."pekerjaan_creation_status_enum" NOT NULL DEFAULT 'created', "progress_status" "public"."pekerjaan_progress_status_enum" NOT NULL DEFAULT 'on_track', CONSTRAINT "PK_e051ee17390f3fb8d544e9f1e8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_milestone_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."project_milestone_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "project_milestone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pekerjaan_id" uuid NOT NULL, "milestone_name" character varying NOT NULL, "milestone_description" text, "due_date" date, "status" "public"."project_milestone_status_enum" NOT NULL DEFAULT 'pending', "completion_percentage" integer NOT NULL DEFAULT '0', "priority" "public"."project_milestone_priority_enum" NOT NULL DEFAULT 'medium', "order_index" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a9da5fbeade8826432de525d1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_schema"."surat_tagihan_non_bulanan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "master_document_list_id" uuid NOT NULL, "version_number" integer NOT NULL, "is_latest" boolean NOT NULL DEFAULT true, "uploaded_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "client_id" uuid NOT NULL, "document_description" text NOT NULL, "Nilai Kontrak" numeric(19,4) NOT NULL, "DPP_nilai_lain" numeric(19,4) NOT NULL, "PPN_12" numeric(19,4) NOT NULL, "PPh_23" numeric(19,4) NOT NULL, "Total_tagihan" numeric(19,4) NOT NULL, "bank_info" jsonb, "SPK_id" uuid NOT NULL, CONSTRAINT "PK_1d2e0dc0ee36a9a6098358f90df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_schema"."surat_perjanjian_kerja" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "master_document_list_id" uuid NOT NULL, "version_number" integer NOT NULL, "is_latest" boolean NOT NULL DEFAULT true, "uploaded_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "client_id" uuid NOT NULL, "document_description" text NOT NULL, "start_date" date NOT NULL, "end_date" date, "project_fee" numeric(19,4) NOT NULL, "payment_installment" integer NOT NULL, "isIncludeVAT" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b8c5e1c8aa3d7bad034095f294e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_schema"."surat_penawaran" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "master_document_list_id" uuid NOT NULL, "version_number" integer NOT NULL, "is_latest" boolean NOT NULL DEFAULT true, "uploaded_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "client_id" uuid NOT NULL, "document_description" text NOT NULL, "offered_service" text NOT NULL, "person_in_charge" uuid, CONSTRAINT "PK_4173a0ba7e5a1edc8705132ee4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "master_client_list" ADD CONSTRAINT "FK_44d68060c4b60e724efa7a06fde" FOREIGN KEY ("type_id") REFERENCES "client_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."master_document_list" ADD CONSTRAINT "FK_382432e36c657489e55a029dba9" FOREIGN KEY ("document_type_id") REFERENCES "document_schema"."document_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."master_document_list" ADD CONSTRAINT "FK_74012df3684de4e2e06ca3e8697" FOREIGN KEY ("created_by") REFERENCES "identity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."master_document_list" ADD CONSTRAINT "FK_b97ac12d956e89e50f649b98c44" FOREIGN KEY ("master_division_list_id") REFERENCES "master_division_list"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."master_document_list" ADD CONSTRAINT "FK_50b6d79f499f9d51354fc5a016e" FOREIGN KEY ("master_company_list_id") REFERENCES "master_company_list"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_tugas" ADD CONSTRAINT "FK_ec05272b067c6240a9c9fdfb063" FOREIGN KEY ("master_document_list_id") REFERENCES "document_schema"."master_document_list"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_tugas" ADD CONSTRAINT "FK_ebe3439372f2b2aa515c3d60612" FOREIGN KEY ("client_id") REFERENCES "master_client_list"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_tugas" ADD CONSTRAINT "FK_4360551ac02b6a9001af043c72d" FOREIGN KEY ("signer") REFERENCES "identity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."tim_penugasan" ADD CONSTRAINT "FK_036942e8deb17559c7a16397e29" FOREIGN KEY ("surat_tugas_id") REFERENCES "document_schema"."surat_tugas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."tim_penugasan" ADD CONSTRAINT "FK_1bf0f8b83e10e0249dedef3ed91" FOREIGN KEY ("personnel_id") REFERENCES "identity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_installment" ADD CONSTRAINT "FK_2c64c375dd052c8bbf181f5f7a4" FOREIGN KEY ("pekerjaan_id") REFERENCES "pekerjaan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_installment" ADD CONSTRAINT "FK_a2e51691503614ea53392ba48b8" FOREIGN KEY ("project_milestone_id") REFERENCES "project_milestone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_milestone" ADD CONSTRAINT "FK_3382ecc9bf33e02b1c7ec2f2cf1" FOREIGN KEY ("pekerjaan_id") REFERENCES "pekerjaan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_tagihan_non_bulanan" ADD CONSTRAINT "FK_5286ff63340639a92127d771251" FOREIGN KEY ("master_document_list_id") REFERENCES "document_schema"."master_document_list"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_perjanjian_kerja" ADD CONSTRAINT "FK_893e864b8eb64404bc388ad4e09" FOREIGN KEY ("master_document_list_id") REFERENCES "document_schema"."master_document_list"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_penawaran" ADD CONSTRAINT "FK_06cf71a3892c3b1721980fb7123" FOREIGN KEY ("master_document_list_id") REFERENCES "document_schema"."master_document_list"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_penawaran" ADD CONSTRAINT "FK_5d773b2cd49d071c67d11c2bf32" FOREIGN KEY ("person_in_charge") REFERENCES "identity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_penawaran" DROP CONSTRAINT "FK_5d773b2cd49d071c67d11c2bf32"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_penawaran" DROP CONSTRAINT "FK_06cf71a3892c3b1721980fb7123"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_perjanjian_kerja" DROP CONSTRAINT "FK_893e864b8eb64404bc388ad4e09"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_tagihan_non_bulanan" DROP CONSTRAINT "FK_5286ff63340639a92127d771251"`);
        await queryRunner.query(`ALTER TABLE "project_milestone" DROP CONSTRAINT "FK_3382ecc9bf33e02b1c7ec2f2cf1"`);
        await queryRunner.query(`ALTER TABLE "payment_installment" DROP CONSTRAINT "FK_a2e51691503614ea53392ba48b8"`);
        await queryRunner.query(`ALTER TABLE "payment_installment" DROP CONSTRAINT "FK_2c64c375dd052c8bbf181f5f7a4"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."tim_penugasan" DROP CONSTRAINT "FK_1bf0f8b83e10e0249dedef3ed91"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."tim_penugasan" DROP CONSTRAINT "FK_036942e8deb17559c7a16397e29"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_tugas" DROP CONSTRAINT "FK_4360551ac02b6a9001af043c72d"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_tugas" DROP CONSTRAINT "FK_ebe3439372f2b2aa515c3d60612"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."surat_tugas" DROP CONSTRAINT "FK_ec05272b067c6240a9c9fdfb063"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."master_document_list" DROP CONSTRAINT "FK_50b6d79f499f9d51354fc5a016e"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."master_document_list" DROP CONSTRAINT "FK_b97ac12d956e89e50f649b98c44"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."master_document_list" DROP CONSTRAINT "FK_74012df3684de4e2e06ca3e8697"`);
        await queryRunner.query(`ALTER TABLE "document_schema"."master_document_list" DROP CONSTRAINT "FK_382432e36c657489e55a029dba9"`);
        await queryRunner.query(`ALTER TABLE "master_client_list" DROP CONSTRAINT "FK_44d68060c4b60e724efa7a06fde"`);
        await queryRunner.query(`DROP TABLE "document_schema"."surat_penawaran"`);
        await queryRunner.query(`DROP TABLE "document_schema"."surat_perjanjian_kerja"`);
        await queryRunner.query(`DROP TABLE "document_schema"."surat_tagihan_non_bulanan"`);
        await queryRunner.query(`DROP TABLE "project_milestone"`);
        await queryRunner.query(`DROP TYPE "public"."project_milestone_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."project_milestone_status_enum"`);
        await queryRunner.query(`DROP TABLE "pekerjaan"`);
        await queryRunner.query(`DROP TYPE "public"."pekerjaan_progress_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pekerjaan_creation_status_enum"`);
        await queryRunner.query(`DROP TABLE "payment_installment"`);
        await queryRunner.query(`DROP TYPE "public"."payment_installment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_installment_trigger_type_enum"`);
        await queryRunner.query(`DROP TABLE "document_schema"."tim_penugasan"`);
        await queryRunner.query(`DROP TABLE "document_schema"."surat_tugas"`);
        await queryRunner.query(`DROP TABLE "document_schema"."master_document_list"`);
        await queryRunner.query(`DROP TYPE "document_schema"."master_document_list_document_status_enum"`);
        await queryRunner.query(`DROP TABLE "document_schema"."document_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d12ecd5a215a1f5529660e471"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44deca8dc7cf45dcc6731a7d19"`);
        await queryRunner.query(`DROP TABLE "identity"`);
        await queryRunner.query(`DROP TYPE "public"."identity_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."identity_status_enum"`);
        await queryRunner.query(`DROP TABLE "master_client_list"`);
        await queryRunner.query(`DROP TYPE "public"."master_client_list_status_enum"`);
        await queryRunner.query(`DROP TABLE "client_type"`);
        await queryRunner.query(`DROP TABLE "master_company_list"`);
        await queryRunner.query(`DROP TABLE "master_division_list"`);
    }

}
